"""empty message

Revision ID: 5476e49289ad
Revises: 
Create Date: 2017-04-20 22:59:22.020511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5476e49289ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('city_name', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('city_name')
    )
    op.create_table('passenger',
    sa.Column('pass_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('pass_id')
    )
    op.create_index(op.f('ix_passenger_first_name'), 'passenger', ['first_name'], unique=False)
    op.create_index(op.f('ix_passenger_last_name'), 'passenger', ['last_name'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=True),
    sa.Column('user_email', sa.String(length=120), nullable=True),
    sa.Column('user_role', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_login'), 'user', ['login'], unique=True)
    op.create_index(op.f('ix_user_user_email'), 'user', ['user_email'], unique=True)
    op.create_table('flight',
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('flight_code', sa.VARCHAR(), nullable=True),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('city_arrival', sa.String(), nullable=True),
    sa.Column('city_departure', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['city_arrival'], ['city.city_name'], ),
    sa.ForeignKeyConstraint(['city_departure'], ['city.city_name'], ),
    sa.PrimaryKeyConstraint('flight_id'),
    sa.UniqueConstraint('flight_code')
    )
    op.create_table('reservation',
    sa.Column('reserv_id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=True),
    sa.Column('reserv_flight', sa.Integer(), nullable=True),
    sa.Column('reserv_class', sa.String(length=64), nullable=True),
    sa.Column('seat_number', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['passenger_id'], ['passenger.pass_id'], ),
    sa.ForeignKeyConstraint(['reserv_flight'], ['flight.flight_id'], ),
    sa.PrimaryKeyConstraint('reserv_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    op.drop_table('flight')
    op.drop_index(op.f('ix_user_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_login'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_passenger_last_name'), table_name='passenger')
    op.drop_index(op.f('ix_passenger_first_name'), table_name='passenger')
    op.drop_table('passenger')
    op.drop_table('city')
    # ### end Alembic commands ###
